version: "3.8"

services:
  gateway:
    build:
      context: .
      dockerfile: ./gateway/Dockerfile
    container_name: gateway
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"
    networks:
      - app-network

  auth-db:
    image: postgres:15
    container_name: auth-db
    environment:
      POSTGRES_USER: auth
      POSTGRES_PASSWORD: auth123*
      POSTGRES_DB: auth
    ports:
      - "5432:5432"
    networks:
      - app-network

  auth-api:
    build:
      context: .
      dockerfile: ./auth/Dockerfile
    container_name: auth-api
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://auth-db:5432/auth
      SPRING_DATASOURCE_USERNAME: auth
      SPRING_DATASOURCE_PASSWORD: auth123*
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - auth-db
    networks:
      - app-network

  digitalwallet-db:
    image: postgres:15
    container_name: wallet-db
    environment:
      POSTGRES_USER: wallet
      POSTGRES_PASSWORD: wallet123*
      POSTGRES_DB: digitalwallet
    ports:
      - "5433:5432"
    networks:
      - app-network

  digitalwallet-api:
    build:
      context: .
      dockerfile: ./digitalwallet/Dockerfile
    container_name: wallet-api
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://digitalwallet-db:5432/digitalwallet
      SPRING_DATASOURCE_USERNAME: wallet
      SPRING_DATASOURCE_PASSWORD: wallet123*
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - digitalwallet-db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
